#! /bin/sh

# chkconfig: 2345 55 25
# description: b-datum

# Place this file at /etc/init.d/b-datum (or
# /etc/rc.d/init.d/b-datum) and make symlinks to
#   /etc/rc.d/rc0.d/K02b-datum
#   /etc/rc.d/rc1.d/K02b-datum
#   /etc/rc.d/rc2.d/K02b-datum
#   /etc/rc.d/rc3.d/S98b-datum
#   /etc/rc.d/rc4.d/S98b-datum
#   /etc/rc.d/rc5.d/S98b-datum
# Or, if you have chkconfig, simply:
# chkconfig --add b-datum
#
# Proper init scripts on Linux systems normally require setting lock
# and pid files under /var/run as well as reacting to network
# settings, so you should treat this with care.

# The path that is to be used for the script
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

EXEC=bdatum-backup
DAEMON="/usr/bin/$EXEC"

set -e

# Only start if we can find the postmaster.
test -x $DAEMON ||
{
	echo "$DAEMON not found"
	if [ "$1" = "stop" ]
	then exit 0
	else exit 5
	fi
}

# Parse command line parameters.
case $1 in
  start)
  	echo -n "Starting b-datum: "
	$DAEMON 
	echo "ok"
	;;
  stop)
  	echo -n "Stopping b-datum: "
	killall -HUP $EXEC
	echo "ok
	;;
  *)
  	# Print help
	echo "Usage: $0 {start|stop}" 1>&2
	exit 1
	;;
esac

exit 0

